name: mensageiro
description: Aplicativo de chat simples com Supabase e Material You
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.9.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.2.1
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true